### ISSUE TITLE
Errores en construcción de registros  a partir de existentes

### ISSUE THREAD

**Issue by arypbatista** [gobstones/PyGobstones#21]
PRUEBA 1
type Persona is record{
field nombre
field edad
field apellido
}

program{
p1:=Persona(nombre<-"Vale", edad<-33, apellido<-"De Cristofolo")
p3:= Persona(p1 | edad<-4, nombre <- "pepe")
return (p3)
}

p3 esperaría que tenga 4 años, y se llame "pepe" "De Cristofolo"....  Pero solo cambia la edad, 
También probé:
p3:= Persona(p1 |  nombre <- "pepe", edad<-4)
Y en este caso solo cambia el nombre pero no la edad, asi que solamente estaria funcionando cambiar el primer campo que se pone después del pipe.

Prueba 2
Otro cosa que también probé fue lo que hablamos en la reunión de balance que pasa si los chicos mezclan los tipos:

type Persona is record{
field  nombre 
field  edad
field  apellido
field casado
}

type Profesor is record{
field  legajo
field interino
}

program{
vale:=Profesor( legajo<-4,interino<-True)
p1:=Persona(nombre<-"Vale", edad<-33, apellido<-"De Cristofolo", casado<-True)
p3:= Persona(vale | casado<- not(True),  nombre <- "pepe" , edad<-4)
return (p3)
}
Devuelve:
'Persona(interino <- True, casado <- False, legajo <- 4)'

Fijate que p3 devuelve cualquier cosa, porque es una Persona con los campos del Profesor
Para mi si se puede,  seria mejor que diera error al chequear, o si no se puede al menos que de  BOOM.

Prueba 3
type Persona is record{
field nombre
field edad
field apellido
field casado
}
program{
p1:=Persona(nombre<-"Vale", edad<-33, apellid<-"De Cristofolo", casado<-True, cualquierCosa <-3)
return (p1)
}
Devuelve: "Persona(edad <- 33, nombre <- 'Vale', cualquierCosa <- 3, apellid <- 'De Cristofolo', casado <- True)"

Fijate que en el constructor te deja poner cualquier cosa en los campos, le invente el campo cualquierCosa y lo crea sin problemas, lo mismo que apellido, a propósito le saque la o final.

Me ha pasado este cuatrimestre que los chicos escribian mal el nombre de los campos entonces despues daba error:
Por ejemplo:

type Persona is record{
field nombre
field edad
field apellido
field casado
}

program{
p1:=Persona(nombre<-"Vale", edad<-33, apellid<-"De Cristofolo", casado<-True, cualquierCosa <-3)
return (apellido(p1))
}

Esto dio BOOM, pero la descripción del BOOM los marea porque toma como válidos los campos del constructor en vez de los campos de la definición del tipo.

 -> Boom !!!
-> El registro no posee un campo llamado "apellido"  Y ESTO NO ES CIERTO!!
Los campos disponibles en este registro son: edad, nombre, apellid, cualquierCosa, casado..... por error del alumno.. no coincide con la definicion del tipo

En:
entrypoint program (None:16)
Valores de los identificadores:
p1: Persona(edad <- 33, nombre <- 'Vale', apellid <- 'De Cristofolo', cualquierCosa <- 3, casado <- True)

**Comment by arypbatista** [comment]
Falta solucionar el error de la prueba 3, con respecto a que es posible definir un valor para un campo no definido. Sin embargo, apellido(p1) falla por no estar definido en el registro.

**Comment by lvolinier** [comment]
@arypbatista sobre el comment anterior... considero que es un error más grave todavía! De hecho, este error es un caso particular de un error más grande. Te levanto un issue aparte

**Comment by arypbatista** [comment]
Solucionado en la 1.3.1
