### ISSUE TITLE
Generar el AST sin ejecutar el programa

### ISSUE THREAD

**Issue by faloi** [gobstones/PyGobstones#32]
Sería interesante que si se le pasa el flag `--print-ast` al compilador/intérprete no se ejecute el código, sino que simplemente se genere el AST.

Actualmente con @flbulgarelli estamos usando el `gbs.py` en https://github.com/uqbar-project/mumuki-gobstones-server para hacer análisis estático de programas Gobstones, y este comportamiento nos obliga a definir un tablero inicial cuando lo que queremos hacer es completamente independiente de la ejecución (por ahora sólo estamos chequeando que un cierto código llame a un procedimiento, pero pronto vamos a agregar más chequeos).

En esta misma línea, sería ideal que pudieran generarse ASTs de programas "incompletos". Lo que nos interesa acá es saltear el chequeo de que los procedimientos/funciones estén definidos, para así poder correr las validaciones sólo sobre el código submitteado por el alumno, sin tener en consideración el código extra que agrega el docente a la solución.

**Comment by arypbatista** [comment]
Había un flag de no ejecución creo. Te copas a agregarlo vos? Es tocar el
archivo gbs.py nomás. Estaria bueno también poder retornar el AST en
formato JSON

**Comment by faloi** [comment]
Dale, lo miro. Debería(mo)s mover esta issue a pygobstones-lang.

Lo del JSON me parece piola pero probablemente lleve un poco más de laburo, así que por ahora [lo cargué como issue](https://github.com/gobstones/PyGobstones-Lang/issues/3). Pero también me interesa y de hecho lo voy a necesitar cuando haga chequeos un poco más inteligentes.

Veo que hay unos cuantos tests... me explicás cómo correrlos? No la tengo clara en Python y no quiero romper nada :see_no_evil:

**Comment by arypbatista** [comment]
Te parece hacer un Skype y te cuento un par de cosas? Algún día a la noche

**Comment by faloi** [comment]
Esto fue arreglado en https://github.com/gobstones/PyGobstones-Lang/commit/27a5e3e73f28ac9b34a2d89f3eb132d9deee7766
