### ISSUE TITLE
Problemas con registros

### ISSUE THREAD

**Issue by ebonelli** [gobstones/PyGobstones#33]
[Reportado por Flavia el 	Thu, Jun 4, 2015 at 2:18 PM]

Defino el siguiente tipo y deseo crear una nueva persona con nombre y dni modificados 

type Persona is record {
     field dni
     field esMasculino
     field direccion
}

program{

per:=Persona(dni<-1, esMasculino <-True , direccion <- 2)
return (Persona(per | dni<-3, direccion <- 3))
}

Siempre modifica unicamente el primer campo, o sea, en este caso, el dni.

Por otro lado, hacer en un program

program {
   juan := Persona(...)
   pepe := Persona(...)
   jose  := Persona(...)
   return(juan, pepe, jose)
}

hace que en el listado de variables de retorno, todas se muestran con los valores de juan.

**Comment by arypbatista** [comment]
Este bug ya está solucionado. Falta subir la nueva versión de PyGobstones.
