### ISSUE TITLE
La construcción de Registros no se basa en la definición declarada

### ISSUE THREAD

**Issue by lvolinier** [gobstones/PyGobstones#36]
Establecida esta definición de registros:

```Python
type Persona is record {
	field nombre
	field dni
	field domicilio
}

type Alumno is record {
	field datos /* <Persona> */
	field legajo
	field matAprobadas
}
```
Se prueban las siguientes lineas en un `program { }`

Se crea una persona: todo como lo esperado.
```Python
pA := Persona(nombre <- Rojo, dni <- 1, domicilio <- Norte)
```

Ahora, si hago una construcción parcial, el chequeador me dice que "todo bien" y la ejecución funciona y me denota un registro "parcialmente" completo. 
```Python
pB := Persona(nombre <- Rojo)
```
Esto debería, al menos, ser alertado por el Chequeador. Explota cuando se quiere denotar el valor no definido: 
```Python
elDni := dni(pB)
```

El siguiente caso debería ser un error en el chequeador:
```Python
pC := Persona(nombre <- Rojo, docNro <- 3)
```
El chequeador falla cuando:
```Python
elDoc := docNro(pC)
```

Esta inconsistencia en cuanto a los tipos definidos, lleva a confunciones que pasa desapercibidas y pueden perjudicar el proceso de aprendizaje:
```Python
// Error que cometió el alumno:
aA := Alumno(nombre <- Rojo, dni <- 1, domicilio <- Norte, legajo <- 101, matAprobadas <- 0)```
// Y lo peor es que estaba confundido porque pensaba que esto SÍ funciona
aB := Alumno(aA | esEmpleado <- True)	
return (pA, aB)
```

**Comment by lvolinier** [comment]
Esto está relacionado con #21 y #19

**Comment by arypbatista** [comment]
Solucionado en la 1.3.1
