### ISSUE TITLE
No se guardan los archivos si el nombre tiene un punto

### ISSUE THREAD

**Issue by faloi** [gobstones/PyGobstones#39]
El problema es que no sólo no se guardan, sino que no te muestra ningún tipo de mensaje. Hoy me pasó que a raíz de eso 3 alumnos perdieron su trabajo :cry:

**Comment by arypbatista** [comment]
Al guardar un *.gbs?

**Comment by faloi** [comment]
Sí. Peeeeeero acabo de probar en Ubuntu y no pasa, esto fue en Huayra.

Me armo una VM y pruebo de nuevo.

**Comment by arypbatista** [comment]
Estoy viendolo igualmente. Voy a armar unos tests para el guardado de
archivos

**Comment by arypbatista** [comment]
resuelto.
