### ISSUE TITLE
'ascii' codec can't decode byte 0xc3 in position 39: ordinal not in range(128)

### ISSUE THREAD

**Issue by asanzo** [gobstones/PyGobstones#46]
Version 1.5.0 (sacada de un mail que mandó Ary), aunque dice versión 1.4 en el Acerca de.
Esto arroja el error mencionado en la consolita:
program {
  Mover(Sur)
}

Pero esto no:
program {
    //  Mover(Sur)
}
Tampoco tira error si la instrucción es Mover(Norte), Este ú Oeste.

WindowsXP 32bit

**Comment by arypbatista** [comment]
Arreglado (creo) en la 1.5.1. Hoy mergeo a master y subo la versión.

**Comment by Laski** [comment]
Hola, a mí me mordió hoy en la versión 1.5.2

**Comment by arypbatista** [comment]
Hola,

Necesito más información sobre tu error:

- Programa que usaste como input
- Tablero inicial
- Archivos de logs que se encuentran en la carpeta ".pygobstones" en tu
carpeta de usuario.
ej: /home/<user>/.pygobstones  o   C:/Usuarios/<user>/.pygobstones

Saludos
