### ISSUE TITLE
Biblioteca: No se muestran bien los errores de sintaxis 

### ISSUE THREAD

**Issue by asanzo** [gobstones/PyGobstones#47]
Version 1.5.0 (pasada por Ary en un mail)
WinXP 32bits.
Ejemplo Archivo principal:
program{
   Lala(Norte)
}
Biblioteca:
-- Nueva Biblioteca
procedure Lala(n){
	Moverr(n)
}
Output:
'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)

**Comment by arypbatista** [comment]
Solucionado en la 1.5.1
