### ISSUE TITLE
Al ejecutar no sucede nada (sucede aleatoriamente)

### ISSUE THREAD

**Issue by asanzo** [gobstones/PyGobstones#49]
WinXP 32bits + Win7 64
A veces, luego de hacer un cambio y hacer ejecutar, se queda pensando y no muestra la ventana de resultados. Lo ùnico que dice es:
 -> Comienza ejecución || Lenguaje: Gobstones 3.0.0

Desafortunadamente no puedo encontrar el patrón que  hace que se produzca.

**Comment by arypbatista** [comment]
Yo tampoco... es un fucking error con los canales de comunicación inter-proceso... Tengo que poner un hack que descarte mensajes inservibles.. aunque estaría bueno detectar qué introdujo esta anomalía.

**Comment by arypbatista** [comment]
Podrás descargar la 1.5.2 y fijarte si esto sigue? Creo que está solucionado.

Tenia al auto-completado utilizando el mismo sistema que se utiliza para mandar a ejecutar programas en un proceso aparte. Creo que lo que ocurría es que las instancias se "robaban" los mensajes entre sí. Ya no debería ocurrir, el auto completado utiliza la implementación del lenguaje directamente.

Avisame si esto está OK asi cierro el issue.

**Comment by asanzo** [comment]
Esta semana uso ese y t aviso.
