### ISSUE TITLE
Ctrl + C sobre la consola

### ISSUE THREAD

**Issue by asanzo** [gobstones/PyGobstones#50]
WinXP 32bits
Cuando intento hacer Ctrl + C sobre la consola para copiar, no funciona (aunque sí me deja seleccionar)
Es un poco molesto y antiintuitivo tener que hacer click derecho -> Copiar
Creo que es una barrera tonta, pero una barrera al fin, para que alguien pueda hacer consultas al docete ò un reporte de errores.
Es realmente menor, pero està en mi wishlist que me acerca a la felicidad Gobstoniana :)

**Comment by arypbatista** [comment]
Ya hay abierto un issue para esto. Te invito a colaborar con este cambio :)
