### ISSUE TITLE
Mensaje Criptico al no incluir program

### ISSUE THREAD

**Issue by alanrodas** [gobstones/PyGobstones#52]
Al ejecutar un programa que posee procedimiento, pero no un program, la conola debería mostrar un mensaje de error acorde a esto.

Se obtiene:
'NoneType' object has no attribute 'children'
Se esperaba:
Un programa gobstones debe poseer un program (O algún mensaje similar)
Reproducibilidad: Siempre
Versión: 1.5.1

**Comment by arypbatista** [comment]
Resuelto en 1.5.2
