### ISSUE TITLE
Error con los proyectores de los registros

### ISSUE THREAD

**Issue by Nykros** [gobstones/PyGobstones#57]
PyGobstones 1.2.1 / XGobstones 1.0.0

Tal vez ya lo han corregido, pero sino, el siguiente codigo hace que se el programa no termine. O bien deberia dar un error de tipo en tiempo de compilacion o un BUM en runtime:

type Usuario is record {
  field id}

program {
  x := id(5)
}

**Comment by arypbatista** [comment]
Hola, la última versión es la 1.5.3, podés descargarla de acá: http://gobstones.github.io/descargas/

Saludos,
