### ISSUE TITLE
Tableros no se guardan/cargan en ruta con caracteres especiales

### ISSUE THREAD

**Issue by gobstones-admin** [gobstones/PyGobstones#6]
Si la ruta donde queremos guardar o tenemos guardado un tablero hay algún carácter especial como ñ o á, hay problemas para cargar o guardarlo respectivamente. Sucede en Win7 64-bit. Desconozco en otros sistemas y también si sucede en todos los casos

**Comment by arypbatista** [comment]
Resuelto.
